name: CampusFrance Behave Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install deps
      shell: powershell
      run: |
        pip install --upgrade pip
        pip install behave selenium webdriver-manager behave-html-formatter
        
    - name: Fix Python path
      shell: powershell
      run: |
        $env:PYTHONPATH = "$env:PYTHONPATH;$PWD\utils"
        Write-Output "PYTHONPATH=$env:PYTHONPATH"
        
    - name: Run Behave + HTML Report
      env:
        HEADLESS: true
      shell: powershell
      run: |
        Write-Output "DEBUG Structure:"
        Get-ChildItem features -Recurse
        
        behave -f html -o report.html --no-capture --verbose
        
    - name: Upload Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: behave-report-html
        path: report.html
